name: CI/CD

on:
  workflow_call:
    inputs:
      login-server:
        required: true
        type: string
      

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    -  uses: actions/checkout@v4
    -  name: Login to registry
       uses: azure/docker-login@v1
       with:
         login-server: ${{ inputs.login-server }}
         username: ${{ env.REGISTRY_USERNAME }}
         password: ${{ env.REGISTRY_PASSWORD }}
    -  run: |
         docker build -t ${{ inputs.login-server }}/myapp:${{ github.sha }} .
         docker push ${{ inputs.login-server }}/myapp:${{ github.sha }}
