name: CI/CD

on:
  workflow_call:
    inputs:
      login-server:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
      

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    -  uses: actions/checkout@v4
    -  name: Login to registry
       uses: azure/docker-login@v1
       with:
         login-server: ${{ inputs.login-server }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_PASSWORD }}
    -  run: |
         docker build -t githubactionsreusableregistry.azurecr.io/myapp:${{ github.sha }} .
         docker push githubactionsreusableregistry.azurecr.io/myapp:${{ github.sha }}
